/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import java.util.ArrayList;
import Database.DBStatement;
import Database.Utility;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.*;

/**
 *
 * @author Nacabacuzz
 */
public class SeatTransaction extends javax.swing.JFrame {

    /**
     * Creates new form DirectorMain
     */
    float allSumPrice = 0,discountPrice = 0,normalPrice,deluxePrice;
    int discount=0,point,deluxeSelected=0,normalSelected=0;
    String cardID,movie,startTime,theaterID,showtimeID="";
    public SeatTransaction() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        jToggleButton1.setEnabled(false);jToggleButton2.setEnabled(false);jToggleButton3.setEnabled(false);jToggleButton4.setEnabled(false);jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);jToggleButton7.setEnabled(false);jToggleButton8.setEnabled(false);jToggleButton9.setEnabled(false);jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);jToggleButton12.setEnabled(false);jToggleButton13.setEnabled(false);jToggleButton14.setEnabled(false);jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);jToggleButton17.setEnabled(false);jToggleButton18.setEnabled(false);jToggleButton19.setEnabled(false);jToggleButton20.setEnabled(false);
        jToggleButton21.setEnabled(false);jToggleButton22.setEnabled(false);jToggleButton23.setEnabled(false);jToggleButton24.setEnabled(false);jToggleButton25.setEnabled(false);
        ArrayList <String> arList=new ArrayList<String>();
        int num = Database.DBStatement.numOfRow("Select count(*) From Transaction");
        String tran = Database.Utility.increaseID(Database.DBStatement.queryID("Select * From transaction", num),1);
        jLabel33.setText(tran);
        jLabel35.setText(Database.DBConnection.branch);
        jLabel37.setText(Database.Utility.getCurDate(1));
        jLabel11.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        
        DBStatement.DBQuery("Select Price From SeatPrice where seatType = 'Normal'",arList,1);
        normalPrice = Float.parseFloat(arList.get(0));
        DBStatement.DBQuery("Select Price From SeatPrice where seatType = 'Deluxe'",arList,1);
        deluxePrice = Float.parseFloat(arList.get(0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seat Transaction");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel1.setText("ขายตั๋วที่นั่ง");

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel3.setText("หมายเลขบัตร");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("ตกลง");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel4.setText("แต้มที่มี : ");

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel6.setText("แต้ม");

        jLabel23.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel23.setText("ราคารวมสุทธิ");

        jLabel24.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel24.setText("บาท");

        jLabel25.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("0");

        jLabel26.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel26.setText("รับเงิน");

        jTextField2.setFont(new java.awt.Font("AngsanaUPC", 0, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel27.setText("บาท");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("ตกลง");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel28.setText("ส่วนลด");

        jLabel29.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("0");

        jLabel30.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel30.setText("บาท");

        jLabel31.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel31.setText("0 %");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("คิดเงิน");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel32.setText("หมายเลขใบเสร็จ");

        jLabel33.setText("jLabel33");

        jLabel34.setText("สาขา");

        jLabel35.setText("jLabel35");

        jLabel10.setFont(new java.awt.Font("AngsanaUPC", 0, 22)); // NOI18N
        jLabel10.setText("เรื่อง");

        DefaultComboBoxModel model = new DefaultComboBoxModel(DBStatement.comboBoxQuery("select distinct movieName from theater t inner join showtime s on t.theaterID = s.theaterID inner join movie m on m.MovieID = s.MovieID "
            + "Where date=curdate() and t.BranchID = '"+Database.DBConnection.branch+"'").toArray());
    jComboBox1.setModel(model);
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("AngsanaUPC", 0, 22)); // NOI18N
    jLabel11.setText("รอบ");

    DefaultComboBoxModel model2 = new DefaultComboBoxModel(DBStatement.comboBoxQuery("select date from theater t inner join showtime s on t.theaterID = s.theaterID "
        + "inner join movie m on m.MovieID = s.MovieID Where date = curdate() and m.MovieName = '"+movie+"' and t.BranchID = '"+Database.DBConnection.branch+"' and date=curdate()").toArray());
jComboBox2.setModel(model2);
jComboBox2.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox2ActionPerformed(evt);
    }
    });

    jLabel36.setText("วันที่");

    jLabel37.setText("jLabel37");

    jLabel12.setFont(new java.awt.Font("AngsanaUPC", 0, 22)); // NOI18N
    jLabel12.setText("โรงที่");

    jLabel13.setFont(new java.awt.Font("AngsanaUPC", 0, 22)); // NOI18N
    jLabel13.setText("jLabel13");

    jLabel2.setText("-----------------------------------หน้าจอ-----------------------------------");

    jLabel38.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
    jLabel38.setForeground(new java.awt.Color(204, 0, 0));
    jLabel38.setText("แถว A");

    jLabel39.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
    jLabel39.setForeground(new java.awt.Color(204, 0, 0));
    jLabel39.setText("แถว B");

    jLabel40.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
    jLabel40.setText("แถว C");

    jLabel41.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
    jLabel41.setText("แถว D");

    jLabel42.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
    jLabel42.setText("แถว E");

    jToggleButton1.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton1.setText("A1");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton1ActionPerformed(evt);
        }
    });

    jToggleButton2.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton2.setText("A2");
    jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton2ActionPerformed(evt);
        }
    });

    jToggleButton3.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton3.setText("A3");
    jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton3ActionPerformed(evt);
        }
    });

    jToggleButton4.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton4.setText("A4");
    jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton4ActionPerformed(evt);
        }
    });

    jToggleButton5.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton5.setText("A5");
    jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton5ActionPerformed(evt);
        }
    });

    jToggleButton6.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton6.setText("B1");
    jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton6ActionPerformed(evt);
        }
    });

    jToggleButton7.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton7.setText("B2");
    jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton7ActionPerformed(evt);
        }
    });

    jToggleButton8.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton8.setText("B3");
    jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton8ActionPerformed(evt);
        }
    });

    jToggleButton9.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton9.setText("B4");
    jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton9ActionPerformed(evt);
        }
    });

    jToggleButton10.setForeground(new java.awt.Color(204, 0, 0));
    jToggleButton10.setText("B5");
    jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton10ActionPerformed(evt);
        }
    });

    jToggleButton11.setText("C1");
    jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton11ActionPerformed(evt);
        }
    });

    jToggleButton12.setText("C2");
    jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton12ActionPerformed(evt);
        }
    });

    jToggleButton13.setText("C3");
    jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton13ActionPerformed(evt);
        }
    });

    jToggleButton14.setText("C4");
    jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton14ActionPerformed(evt);
        }
    });

    jToggleButton15.setText("C5");
    jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton15ActionPerformed(evt);
        }
    });

    jToggleButton16.setText("D1");
    jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton16ActionPerformed(evt);
        }
    });

    jToggleButton17.setText("D2");
    jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton17ActionPerformed(evt);
        }
    });

    jToggleButton18.setText("D3");
    jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton18ActionPerformed(evt);
        }
    });

    jToggleButton19.setText("D4");
    jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton19ActionPerformed(evt);
        }
    });

    jToggleButton20.setText("D5");
    jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton20ActionPerformed(evt);
        }
    });

    jToggleButton21.setText("E1");
    jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton21ActionPerformed(evt);
        }
    });

    jToggleButton22.setText("E2");
    jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton22ActionPerformed(evt);
        }
    });

    jToggleButton23.setText("E3");
    jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton23ActionPerformed(evt);
        }
    });

    jToggleButton24.setText("E4");
    jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton24ActionPerformed(evt);
        }
    });

    jToggleButton25.setText("E5");
    jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton25ActionPerformed(evt);
        }
    });

    jLabel7.setText("สีดำ : Normal seat");

    jLabel8.setForeground(new java.awt.Color(204, 0, 0));
    jLabel8.setText("สีแดง : Deluxe seat ");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(77, 77, 77)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel36)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel33))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel35))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(5, 5, 5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)))
            .addGap(20, 20, 20))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel41))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel8)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton6)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton7)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton8)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton11)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton12)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton13)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton14)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton16)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton17)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton18)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton19)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton20))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton21)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton22)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton23)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton24)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton25))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton3)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(0, 84, Short.MAX_VALUE))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12)
                .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel42)
                .addComponent(jToggleButton21)
                .addComponent(jToggleButton22)
                .addComponent(jToggleButton23)
                .addComponent(jToggleButton24)
                .addComponent(jToggleButton25))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel41)
                .addComponent(jToggleButton16)
                .addComponent(jToggleButton17)
                .addComponent(jToggleButton18)
                .addComponent(jToggleButton19)
                .addComponent(jToggleButton20))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel40)
                .addComponent(jToggleButton11)
                .addComponent(jToggleButton12)
                .addComponent(jToggleButton13)
                .addComponent(jToggleButton14)
                .addComponent(jToggleButton15))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel39)
                .addComponent(jToggleButton6)
                .addComponent(jToggleButton7)
                .addComponent(jToggleButton8)
                .addComponent(jToggleButton9)
                .addComponent(jToggleButton10))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel38)
                .addComponent(jToggleButton1)
                .addComponent(jToggleButton2)
                .addComponent(jToggleButton3)
                .addComponent(jToggleButton4)
                .addComponent(jToggleButton5))
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel25)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))))
            .addGap(20, 20, 20))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList <String> arList=new ArrayList<String>();
        ArrayList <String> arList2=new ArrayList<String>();
        cardID = jTextField1.getText();
        if(cardID.equals("")==true){
            jLabel31.setText("0 %");
            jLabel5.setText("0");
            discount = 0;
        }
        else{
            try{
            DBStatement.DBQuery("Select * From MemberCard Where CardID = '"+cardID+"'",arList,5);

            if(Utility.getCurDate(2).compareTo(arList.get(4))<0){
                DBStatement.DBQuery("Select Discount From MemberCardType Where Type = '"+arList.get(3)+"'",arList2,1);
                jLabel5.setText(arList.get(2));
                point = Integer.parseInt(arList.get(2));
                jLabel31.setText(arList2.get(0)+" %");
                discount = Integer.parseInt(arList2.get(0));
             }
            else{
                JOptionPane.showMessageDialog(null, "บัตรหมดอายุแล้ว");
             }
            }catch(IndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "ไม่พบหมายเลขบัตร");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        float money,change;
        ArrayList <String> arList4=new ArrayList<String>();
        money = Integer.parseInt(jTextField2.getText());
        if(money<allSumPrice){
            JOptionPane.showMessageDialog(null, "เงินไม่เพียงพอ");
        }
        else{
            change = money-allSumPrice;
            JOptionPane.showMessageDialog(null, "เงินทอน : "+change+" บาท");
            JOptionPane.showMessageDialog(null, "เสร็จสิ้น");
            String seatID;
            
            if(discount == 0){
                DBStatement.DBupdate("insert into transaction value ('"+jLabel33.getText()+
                    "',null,'"+showtimeID+"',"+allSumPrice+")");
            }
            else{
                DBStatement.DBupdate("insert into transaction value ('"+jLabel33.getText()+
                    "','"+cardID+"','"+showtimeID+"',"+allSumPrice+")");
                point=point+((int)allSumPrice/50);
                DBStatement.DBupdate("update membercard set point = "+point+" where cardid ='"+cardID+"'");
            }
            
            if(jToggleButton1.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'A1'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton2.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'A2'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton3.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'A3'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton4.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'A4'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton5.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'A5'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton6.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'B1'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton7.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'B2'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton8.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'B3'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton9.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'B4'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton10.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'B5'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton11.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'C1'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton12.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'C2'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton13.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'C3'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton14.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'C4'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton15.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'C5'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton16.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'D1'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton17.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'D2'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton18.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'D3'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton19.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'D4'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton20.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'D5'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton21.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'E1'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton22.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'E2'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton23.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'E3'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton24.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'E4'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            if(jToggleButton25.isSelected()==true){
                DBStatement.DBQuery("select seatid from seat where theaterid ='"+theaterID+"' and seatNO = 'E5'",arList4,1);
                seatID = arList4.get(0);
                DBStatement.DBupdate("insert into seattransaction value ('"+jLabel33.getText()+
                    "','"+seatID+"')");
            }
            
            this.setVisible(false);
            this.dispose();
            new SeatTransaction().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        allSumPrice=0;
        if(showtimeID.equals("")==true){
            JOptionPane.showMessageDialog(null, "กรุณาเลือกภาพยนตร์และรอบฉาย");
        }
        allSumPrice = deluxeSelected*deluxePrice + normalSelected*normalPrice;
        discountPrice = allSumPrice*discount/100;
        allSumPrice -= discountPrice;
        jLabel29.setText(Float.toString(discountPrice));
        jLabel25.setText(Float.toString(allSumPrice));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jToggleButton1.setEnabled(false);jToggleButton2.setEnabled(false);jToggleButton3.setEnabled(false);jToggleButton4.setEnabled(false);jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);jToggleButton7.setEnabled(false);jToggleButton8.setEnabled(false);jToggleButton9.setEnabled(false);jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);jToggleButton12.setEnabled(false);jToggleButton13.setEnabled(false);jToggleButton14.setEnabled(false);jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);jToggleButton17.setEnabled(false);jToggleButton18.setEnabled(false);jToggleButton19.setEnabled(false);jToggleButton20.setEnabled(false);
        jToggleButton21.setEnabled(false);jToggleButton22.setEnabled(false);jToggleButton23.setEnabled(false);jToggleButton24.setEnabled(false);jToggleButton25.setEnabled(false);
        jLabel11.setVisible(true);
        jComboBox2.setVisible(true);
        movie = jComboBox1.getSelectedItem().toString();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(DBStatement.comboBoxQuery("select StartTime from theater t inner join showtime s on t.theaterID = s.theaterID "
                + "inner join movie m on m.MovieID = s.MovieID Where m.MovieName = '"+movie+"' and t.BranchID = '"+Database.DBConnection.branch+"' and date=curdate()").toArray());
        jComboBox2.setModel(model2);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        jToggleButton1.setEnabled(true);jToggleButton2.setEnabled(true);jToggleButton3.setEnabled(true);jToggleButton4.setEnabled(true);jToggleButton5.setEnabled(true);
        jToggleButton6.setEnabled(true);jToggleButton7.setEnabled(true);jToggleButton8.setEnabled(true);jToggleButton9.setEnabled(true);jToggleButton10.setEnabled(true);
        jToggleButton11.setEnabled(true);jToggleButton12.setEnabled(true);jToggleButton13.setEnabled(true);jToggleButton14.setEnabled(true);jToggleButton15.setEnabled(true);
        jToggleButton16.setEnabled(true);jToggleButton17.setEnabled(true);jToggleButton18.setEnabled(true);jToggleButton19.setEnabled(true);jToggleButton20.setEnabled(true);
        jToggleButton21.setEnabled(true);jToggleButton22.setEnabled(true);jToggleButton23.setEnabled(true);jToggleButton24.setEnabled(true);jToggleButton25.setEnabled(true);
        
        startTime = jComboBox2.getSelectedItem().toString();
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        int i;
        ArrayList <String> arList3 = new ArrayList<String>();
        String seatBought[] = new String[26];
        Arrays.fill(seatBought, "");
        
        DBStatement.DBQuery("select t.TheaterID,TheaterNO,ShowtimeID from theater t inner join showtime s on t.theaterID = s.theaterID "
                + "inner join movie m on m.MovieID = s.MovieID Where m.MovieName = '"+movie+"' and t.BranchID = '"+Database.DBConnection.branch+"' and "
                + "startTime = '"+startTime+"' and date = '"+Database.Utility.getCurDate(2)+"'",arList3,3);
        theaterID = arList3.get(0);
        showtimeID = arList3.get(2);
        jLabel13.setText(arList3.get(1));
        
        DBStatement.querySeat("SELECT seatNO FROM transaction t inner join seattransaction st on t.transactionID = st.TransactionID"
                + " inner join seat s on st.seatID = s.seatID"
                + " WHERE showtimeID = '"+showtimeID+"'",seatBought);
        
        for(i=0;seatBought[i].equals("")==false;i++){
            if(seatBought[i].equals("A1")==true)jToggleButton1.setEnabled(false);
            else if(seatBought[i].equals("A2")==true)jToggleButton2.setEnabled(false);
            else if(seatBought[i].equals("A3")==true)jToggleButton3.setEnabled(false);
            else if(seatBought[i].equals("A4")==true)jToggleButton4.setEnabled(false);
            else if(seatBought[i].equals("A5")==true)jToggleButton5.setEnabled(false);
            else if(seatBought[i].equals("B1")==true)jToggleButton6.setEnabled(false);
            else if(seatBought[i].equals("B2")==true)jToggleButton7.setEnabled(false);
            else if(seatBought[i].equals("B3")==true)jToggleButton8.setEnabled(false);
            else if(seatBought[i].equals("B4")==true)jToggleButton9.setEnabled(false);
            else if(seatBought[i].equals("B5")==true)jToggleButton10.setEnabled(false);
            else if(seatBought[i].equals("C1")==true)jToggleButton11.setEnabled(false);
            else if(seatBought[i].equals("C2")==true)jToggleButton12.setEnabled(false);
            else if(seatBought[i].equals("C3")==true)jToggleButton13.setEnabled(false);
            else if(seatBought[i].equals("C4")==true)jToggleButton14.setEnabled(false);
            else if(seatBought[i].equals("C5")==true)jToggleButton15.setEnabled(false);
            else if(seatBought[i].equals("D1")==true)jToggleButton16.setEnabled(false);
            else if(seatBought[i].equals("D2")==true)jToggleButton17.setEnabled(false);
            else if(seatBought[i].equals("D3")==true)jToggleButton18.setEnabled(false);
            else if(seatBought[i].equals("D4")==true)jToggleButton19.setEnabled(false);
            else if(seatBought[i].equals("D5")==true)jToggleButton20.setEnabled(false);
            else if(seatBought[i].equals("E1")==true)jToggleButton21.setEnabled(false);
            else if(seatBought[i].equals("E2")==true)jToggleButton22.setEnabled(false);
            else if(seatBought[i].equals("E3")==true)jToggleButton23.setEnabled(false);
            else if(seatBought[i].equals("E4")==true)jToggleButton24.setEnabled(false);
            else if(seatBought[i].equals("E5")==true)jToggleButton25.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if(jToggleButton2.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if(jToggleButton3.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if(jToggleButton4.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(jToggleButton5.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
       if(jToggleButton6.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        if(jToggleButton7.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        if(jToggleButton8.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        if(jToggleButton9.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        if(jToggleButton10.isSelected()==true){
            deluxeSelected++;
        }
        else{
            deluxeSelected--;
        }
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        if(jToggleButton11.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        if(jToggleButton12.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        if(jToggleButton13.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        if(jToggleButton14.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        if(jToggleButton15.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        if(jToggleButton16.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        if(jToggleButton17.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        if(jToggleButton18.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        if(jToggleButton19.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        if(jToggleButton21.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        if(jToggleButton22.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        if(jToggleButton23.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        if(jToggleButton24.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        if(jToggleButton25.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        if(jToggleButton20.isSelected()==true){
            normalSelected++;
        }
        else{
            normalSelected--;
        }
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
